version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:17.5.0

jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
#      - run:
#          name: Run tests
#          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: build docker container:
          command: docker build .
        
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=$GIT_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm run release --ci --major --no-git.requireCleanWorkingDir

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master