version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:17.5.0
  environmnet:
    DEV_TENANT_ID: 9a8a0506-3598-4ce5-80fe-6a5307b98ea3
    PROD_TENANT_ID: 97a8d5a4-2662-4e9c-9867-9a4565ec5cb6
    QA_TENANT_ID: 97a8d5a4-2662-4e9c-9867-9a4565ec5cb6
    DOCKER_REPO: public.ecr.aws/p9c8y2k3
    DOCKER_IMAGE_NAME: demo-npm-service

jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=$GIT_TOKEN" >> ~/repo/.npmrc

      - run: npm install
#      - run:
#          name: Run tests
#          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker:
          version: 19.03.13
      - run: 
          name: build docker container
          command: docker build .
        
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish_docker_images:
    working_directory: ~/repo
    docker:
      - image: cimg/node:17.5.0
    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Create and Push Docker container
          command: |
            source ./.circleci/duplo_utils.sh
            tag="$(node -p "require('./package.json').version")-${CIRCLE_BUILD_NUM}"
            docker_tag=$(get_docker_tag $tag)
            echo "Starting build for container: $docker_tag"
            docker build -t $docker_tag . 
            push_container $tag      
      - run:
          name: Update the service
          command: |
            source ./.circleci/duplo_utils.sh
            tag="$(node -p "require('./package.json').version")-${CIRCLE_BUILD_NUM}"
            update_service $tag
workflows:
  version: 2.1
  build_test_publish:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /^v.*/
      - publish_docker_images:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v.*/
