version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:17.5.0

jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=$GIT_TOKEN" >> ~/repo/.npmrc

      - run: npm install
#      - run:
#          name: Run tests
#          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker:
          version: 19.03.13
      - run: 
          name: build docker container
          command: docker build .
        
      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2.1
  build_test:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /^v.*/