version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:17.5.0
  environment:
    DEV_TENANT: dev01
    PROD_TENANT: production
    STAGING_TENANT: staging
    PREPROD_TENANT: preprod
    DOCKER_REPO: public.ecr.aws/p9c8y2k3
    DOCKER_IMAGE_NAME: demo-npm-service
    DUPLO_SERVICE_NAME: nginx
    ECR_REGION: us-west-2
jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=$GIT_TOKEN" >> ~/repo/.npmrc

      - run: npm install
#      - run:
#          name: Run tests
#          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker:
          version: 19.03.13
      - run: 
          name: build docker container
          command: docker build .
        
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish_docker_images:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Create and Push Docker container
          command: |
            source ./.circleci/duplo_utils.sh
            tag=$(node -p "require('./package.json').version")
            docker_tag=$(get_docker_tag $tag)
            echo "Starting build for container: $docker_tag"
            docker build -t $docker_tag . 
            push_container $tag
  deploy_dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Update Dev Environment
          command: |
            source ./.circleci/duplo_utils.sh
            tag=$(git rev-parse HEAD)
            update_service $DEV_TENANT $tag
      - run:
          name: Verify Dev Environment
          command: |
            echo "Verifying dev environment"
  deploy_staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Update staging Environment
          command: |
            source ./.circleci/duplo_utils.sh
            tag=$(git rev-parse HEAD)
            update_service $STAGING_TENANT $tag
      - run:
          name: Verify Dev Environment
          command: |
            echo "Verifying Dev environment"
  deploy_preprod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Update PreProd Environment
          command: |
            source ./.circleci/duplo_utils.sh
            tag=$(git rev-parse HEAD)
            update_service $STAGING_TENANT $tag
      - run:
          name: Verify PreProd Environment
          command: |
            echo "Verifying PreProd Environment"
  deploy_prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Update Prod Environment
          command: |
            source ./.circleci/duplo_utils.sh
            tag=$(git rev-parse HEAD)
            update_service $tag
      - run:
          name: Verify Prod Environment
          command: |
            echo "Verifying Prod Environment"
workflows:
  version: 2.1
  build_test_publish:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /^v.*/
      - publish_docker_images:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^v.*/
